using System;

namespace TKR.Shared.resources
{
    [Flags]
    public enum ConditionEffectIndex : byte
    {
        None = 0,
        Dead = 1,
        Quiet = 2,
        Weak = 3,
        Slowed = 4,
        Sick = 5,
        Dazed = 6,
        Stunned = 7,
        Blind = 8,
        Hallucinating = 9,
        Drunk = 10,
        Confused = 11,
        StunImmune = 12,
        Invisible = 13,
        Paralyzed = 14,
        Speedy = 15,
        Bleeding = 16,
        NotUsed = 17,
        Healing = 18,
        Damaging = 19,
        Berserk = 20,
        Paused = 21,
        Stasis = 22,
        StasisImmune = 23,
        Invincible = 24,
        Invulnerable = 25,
        Armored = 26,
        ArmorBroken = 27,
        Hexed = 28,
        NinjaSpeedy = 29,
        Unstable = 30,
        Curse = 31,
        Darkness = 32,
        Petrify = 33,
        SlowedImmune = 34,
        DazedImmune = 35,
        ParalyzeImmune = 36,
        PetrifyImmune = 37,
        CurseImmune = 38,
        ArmorBreakImmune = 39,
        HPBoost = 40,
        MPBoost = 41,
        AttBoost = 42,
        DefBoost = 43,
        SpdBoost = 44,
        DexBoost = 45,
        VitBoost = 46,
        WisBoost = 47,
        Hidden = 48,
        Regeneration = 49,
        MPTRegeneration = 50,
        NinjaBerserk = 51,
        NinjaDamaging = 52,
        Silenced = 53,
        UnstableImmune = 54
    }
}
