using System;

namespace common.resources
{
    [Flags]
    public enum ConditionEffects : ulong
    {
        Dead = 1 << 0,
        Quiet = 1 << 1,
        Weak = 1 << 2,
        Slowed = 1 << 3,
        Sick = 1 << 4,
        Dazed = 1 << 5,
        Stunned = 1 << 6,
        Blind = 1 << 7,
        Hallucinating = 1 << 8,
        Drunk = 1 << 9,
        Confused = 1 << 10,
        StunImmune = 1 << 11,
        Invisible = 1 << 12,
        Paralyzed = 1 << 13,
        Speedy = 1 << 14,
        Bleeding = 1 << 15,
        NotUsed = 1 << 16,
        Healing = 1 << 17,
        Damaging = 1 << 18,
        Berserk = 1 << 19,
        Paused = 1 << 20,
        Stasis = 1 << 21,
        StasisImmune = 1 << 22,
        Invincible = 1 << 23,
        Invulnerable = 1 << 24,
        Armored = 1 << 25,
        ArmorBroken = 1 << 26,
        Hexed = 1 << 27,
        NinjaSpeedy = 1 << 28,
        Unstable = 1 << 29,
        Curse = 1 << 30,
        Darkness = (ulong)1 << 31,
        Petrify = (ulong)1 << 32,
        SlowedImmune = (ulong)1 << 33,
        DazedImmune = (ulong)1 << 34,
        ParalyzeImmune = (ulong)1 << 35,
        PetrifyImmune = (ulong)1 << 36,
        CurseImmune = (ulong)1 << 37,
        ArmorBreakImmune = (ulong)1 << 38,
        HPBoost = (ulong)1 << 39,
        MPBoost = (ulong)1 << 40,
        AttBoost = (ulong)1 << 41,
        DefBoost = (ulong)1 << 42,
        SpdBoost = (ulong)1 << 43,
        DexBoost = (ulong)1 << 44,
        VitBoost = (ulong)1 << 45,
        WisBoost = (ulong)1 << 46,
        Hidden = (ulong)1 << 47,
        Regeneration = (ulong)1 << 48,
        MPTRegeneration = (ulong)1 << 49,
        NinjaBerserk = (ulong)1 << 50,
        NinjaDamaging = (ulong)1 << 51,
        Silenced = (ulong)1 << 52,
        UnstableImmune = (ulong)1 << 53
    }
}
